// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconChevronDown() {
  return (
    <svg width={24} height={24} fill="none">
      <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="m6 9 6 6 6-6" />
    </svg>
  );
}
