// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconStake({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path fill="currentColor" d="M9 15h6v6H9zM9 3h6v6H9zM15 9h6v6h-6zM3 9h6v6H3z" />
    </svg>
  );
}
