// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconEarn({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M21 3H3v18h18zm-8.999 14.143a5.143 5.143 0 1 0 0-10.286 5.143 5.143 0 0 0 0 10.286"
        clipRule="evenodd"
      />
    </svg>
  );
}
