// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconDownvote({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        d="M5 13.173h5.335L9.182 18h1.643l4.217-4.686V5H8.077L5 8.116v5.058ZM20 13.314h-3.058V5H20v8.314Z"
      />
    </svg>
  );
}
