// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconLeverage() {
  return (
    <svg width={24} height={24} fill="none">
      <path fill="currentColor" d="M3 14.572h6.429V21H3zM9.428 3h11.571v11.571H9.428z" />
    </svg>
  );
}
