// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconChevronSmallUp({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 14 14" width={size} height={size}>
      <path
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M3.5 8.75 7 5.25l3.5 3.5"
      />
    </svg>
  );
}
