// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconNft({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 16 16" width={size} height={size}>
      <path
        fill="currentColor"
        d="M8 5a3 3 0 1 0-3 3V5h3ZM8 5a3 3 0 1 1 3 3V5H8ZM8 11a3 3 0 1 1-3-3v3h3ZM8 11a3 3 0 1 0 3-3v3H8Z"
      />
    </svg>
  );
}
