// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconEllipsis({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path fill="currentColor" d="M4 10h3.2v3.2H4V10ZM10.4 10h3.2v3.2h-3.2V10ZM16.8 10H20v3.2h-3.2V10Z" />
    </svg>
  );
}
