// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconAccount({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        d="M18.5 8.192c0 3.42-2.91 6.191-6.5 6.191s-6.5-2.772-6.5-6.191S8.41 2 12 2s6.5 2.772 6.5 6.192"
      />
      <path fill="currentColor" d="M4 14.381h16V22H4z" />
    </svg>
  );
}
