// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconCross() {
  return (
    <svg width={24} height={24} fill="none">
      <path
        fill="currentColor"
        d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
      />
    </svg>
  );
}
