// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconWarning({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        d="M2 21h20L12 3 2 21Zm10.91-2.842h-1.82v-1.895h1.82v1.895Zm0-3.79h-1.82v-3.79h1.82v3.79Z"
      />
    </svg>
  );
}
