// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconExternal() {
  return (
    <svg width={24} height={24} fill="none">
      <path fill="currentColor" d="M6 6v2h8.59L5 17.59 6.41 19 16 9.41V18h2V6z" />
    </svg>
  );
}
