// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconSettings({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M20.389 7.25 11.944 2.5 3.5 7.25v9.5l8.444 4.75 8.445-4.75v-9.5Zm-8.445 7.917a3.167 3.167 0 1 0 0-6.334 3.167 3.167 0 0 0 0 6.334Z"
        clipRule="evenodd"
      />
    </svg>
  );
}
