// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconUpvote({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        d="M20 9.827h-5.335L15.818 5h-1.643L9.958 9.686V18h6.965L20 14.884V9.827ZM5 9.686h3.058V18H5V9.686Z"
      />
    </svg>
  );
}
