// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconStake() {
  return (
    <svg width={24} height={24} fill="none">
      <path fill="currentColor" d="M9 15h6v6H9zM9 3h6v6H9zM15 9h6v6h-6zM3 9h6v6H3z" />
    </svg>
  );
}
