// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconSuggestion({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 16 16" width={size} height={size}>
      <path
        fill="currentColor"
        d="M4.667 13.333h2.666c0 .734-.6 1.334-1.333 1.334s-1.333-.6-1.333-1.334ZM3.333 12c0 .367.3.667.667.667h4c.367 0 .667-.3.667-.667 0-.367-.3-.667-.667-.667H4c-.367 0-.667.3-.667.667ZM11 6.333c0 2.547-1.773 3.907-2.513 4.334H3.513C2.773 10.24 1 8.88 1 6.333c0-2.76 2.24-5 5-5s5 2.24 5 5Zm3.247-1.42-.914.42.914.42.42.914.42-.914.913-.42-.913-.42-.42-.913-.42.913ZM12.667 4l.626-1.373L14.667 2l-1.374-.627L12.667 0l-.627 1.373L10.667 2l1.373.627L12.667 4Z"
      />
    </svg>
  );
}
