// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconArrowBack({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path fill="currentColor" d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2Z" />
    </svg>
  );
}
