// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconCopy({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M3.523 7.275h10.95v13.95H3.523V7.275Zm1.95 1.95v10.05h7.05V9.225h-7.05Z"
        clipRule="evenodd"
      />
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M9.523 2.775h10.95v13.95h-6.225v-1.95h4.275V4.725h-7.05V7.75h-1.95V2.775Z"
        clipRule="evenodd"
      />
    </svg>
  );
}
