// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconEye({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 16 16" width={size} height={size}>
      <path
        fill="currentColor"
        d="M8.001 3C4.668 3 1.821 5.073.668 8c1.153 2.927 4 5 7.333 5 3.334 0 6.18-2.073 7.334-5-1.154-2.927-4-5-7.334-5Zm0 8.333a3.335 3.335 0 0 1 0-6.666 3.335 3.335 0 0 1 0 6.666Zm0-5.333c-1.106 0-2 .893-2 2s.894 2 2 2c1.107 0 2-.893 2-2s-.893-2-2-2Z"
      />
    </svg>
  );
}
