// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconPlus() {
  return (
    <svg width={24} height={24} fill="none">
      <path fill="currentColor" d="M19 12.998h-6v6h-2v-6H5v-2h6v-6h2v6h6z" />
    </svg>
  );
}
