// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconArrowRight() {
  return (
    <svg width={24} height={24} fill="none">
      <path fill="currentColor" d="m12 4-1.41 1.41L16.17 11H4v2h12.17l-5.58 5.59L12 20l8-8z" />
    </svg>
  );
}
