// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconShieldCheck({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg viewBox="0 0 24 24" fill="none" width={size} height={size}>
      <path
        d="M12 3.19L5 6.3v4.7c0 4.83 2.99 9.36 7 10.93 4.01-1.57 7-6.1 7-10.93V6.3l-7-3.11z"
        stroke="currentColor"
        strokeWidth={1.5}
        fill="none"
      />
      <path d="M9 12l2 2 4-4" stroke="currentColor" strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}
