// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconArrowBack({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="m7.682 12.2 2.807 2.809L9.5 16 5 11.5 9.498 7l.991.991L7.682 10.8H18v1.402z"
        clipRule="evenodd"
      />
    </svg>
  );
}
