// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconLeverage({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path fill="currentColor" d="M3 14.572h6.429V21H3zM9.428 3h11.571v11.571H9.428z" />
    </svg>
  );
}
