// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconDashboard({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path fill="currentColor" d="M2.5 12a9.5 9.5 0 1 1 19 0h-19Z" />
      <path fill="currentColor" d="M16.75 16.75a4.75 4.75 0 1 1-9.5 0 4.75 4.75 0 0 1 9.5 0Z" />
    </svg>
  );
}
