// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconBorrow({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path fill="currentColor" d="M9.364 18.364A9 9 0 0 1 3 21V3a9 9 0 0 1 6.364 15.364" />
      <path fill="currentColor" d="M12 12a9 9 0 0 1 9-9v18a9 9 0 0 1-9-9" />
    </svg>
  );
}
