// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export { IconAccount } from "./IconAccount";
export { IconArrowBack } from "./IconArrowBack";
export { IconArrowRight } from "./IconArrowRight";
export { IconBorrow } from "./IconBorrow";
export { IconChevronDown } from "./IconChevronDown";
export { IconChevronSmallUp } from "./IconChevronSmallUp";
export { IconChevronUp } from "./IconChevronUp";
export { IconCopy } from "./IconCopy";
export { IconCross } from "./IconCross";
export { IconDashboard } from "./IconDashboard";
export { IconDownvote } from "./IconDownvote";
export { IconEarn } from "./IconEarn";
export { IconEdit } from "./IconEdit";
export { IconEllipsis } from "./IconEllipsis";
export { IconExternal } from "./IconExternal";
export { IconEye } from "./IconEye";
export { IconGas } from "./IconGas";
export { IconInfo } from "./IconInfo";
export { IconLeverage } from "./IconLeverage";
export { IconNft } from "./IconNft";
export { IconPlus } from "./IconPlus";
export { IconSearch } from "./IconSearch";
export { IconSettings } from "./IconSettings";
export { IconStake } from "./IconStake";
export { IconSuggestion } from "./IconSuggestion";
export { IconUpvote } from "./IconUpvote";
export { IconWarning } from "./IconWarning";
