import { $ } from "dax-sh";
import * as fs from "node:fs/promises";
import * as path from "path";
import * as v from "valibot";

const dirname = path.dirname(new URL(import.meta.url).pathname);

const rootDir = path.resolve(`${dirname}/../../..`);

const appDir = `${rootDir}/frontend/app`;
const contractsDir = `${rootDir}/contracts`;
const artifactsTmpDir = `${appDir}/liquity-artifacts`;
const appAbisDir = `${appDir}/src/abi`;

// The first name is the contract ABI used in the app,
// the rest are possible names of the contract in the artifacts.
const ABIS = [
  // Protocol
  ["CollateralRegistry"],
  ["HintHelpers"],
  ["MultiTroveGetter"],
  ["WETH"],

  // Collaterals
  ["ActivePool"],
  ["BorrowerOperations"],
  ["CollSurplusPool"],
  ["DefaultPool"],
  ["GasCompZapper"],
  ["GasPool"],
  ["PriceFeed", "PriceFeedTestNet", "PriceFeedMock"],
  ["SortedTroves"],
  ["StabilityPool"],
  ["TroveManager"],
  ["WETHZapper"],
];

const ArtifactSchema = v.object({
  abi: v.array(v.unknown()),
});

async function writeAbiFromArtifact(abi: unknown, abiName: string) {
  const artifact = v.parse(ArtifactSchema, abi);

  const tsFileContent = [
    "// this file was generated by scripts/update-liquity-abis.ts",
    "// please do not edit it manually",
    `export const ${abiName} = ${JSON.stringify(artifact.abi)} as const;`,
  ].join("\n");

  await fs.writeFile(`${appAbisDir}/${abiName}.ts`, tsFileContent);
  await $`dprint --log-level silent fmt ${appAbisDir}/${abiName}.ts`;
}

async function getFirstJsonFound(dir: string) {
  const files = await fs.readdir(dir);
  for (const file of files) {
    if (file.endsWith(".json")) {
      return `${dir}/${file}`;
    }
  }
  throw new Error(`No JSON files found in ${dir}`);
}

async function readJsonFromDir(dir: string, names: string[]) {
  // try to find the file with the names provided
  for (const name of names) {
    console.log(`👉 Trying to find ${name}.json in ${dir}/${name}.sol/…`);
    try {
      return JSON.parse(
        await fs.readFile(`${dir}/${name}.sol/${name}.json`, "utf-8"),
      );
    } catch (_) {}
  }

  // if not found, try the JSON file in the directory
  try {
    console.log(`👉 Trying to find any JSON file in ${dir}/${names[0]}.sol/…`);
    return JSON.parse(
      await fs.readFile(await getFirstJsonFound(`${dir}/${names[0]}.sol`), "utf-8"),
    );
  } catch (_) {}

  return null;
}

async function main() {
  console.log("👉 Building Liquity contracts…\n");
  await $`forge build --root ${contractsDir} --out ${artifactsTmpDir}`;

  console.log("👉 Building promises…");
  await Promise.all(ABIS.map(async (possibleNames) => {
    const abiName = possibleNames[0];

    const abi = await readJsonFromDir(`${artifactsTmpDir}`, possibleNames);

    if (!abi) {
      throw new Error(`Could not find ABI for ${possibleNames.join(", ")}`);
    }

    return writeAbiFromArtifact(abi, abiName);
  }));

  console.log("👉 Removing temporary artifacts…");
  await $`rm -rf ${artifactsTmpDir}`;
  console.log("\nDone.");
  console.log("");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
