#!/bin/bash

# Exit on failure
set -e

export FOUNDRY_PROFILE=e2e
export E2E_RPC_URL="http://localhost:8545"

pidfile=anvil.pid
logfile=anvil.log
anvil_account_0=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

sourcify_version=2.5.0
sourcify_port=5555
sourcify_chains=sourcify-chains.json
sourcify_config=sourcify-config.js

usage() {
  echo "Usage:"
  echo "  ./fork start [--deploy]"
  echo "  ./fork deploy"
  echo "  ./fork e2e [...forge test args]"
  echo "  ./fork stop"
}

die() {
  echo "$@"
  exit 1
}

init_env() {
  # Export vars from .env
  if [ -f .env ]; then
    set -a
    . .env
    set +a
  fi

  [ -n "$FORK_URL" ] || die "Missing FORK_URL"
  [ -n "$FORK_BLOCK_NUMBER" ] || FORK_BLOCK_NUMBER=$(cast block-number --rpc-url "$FORK_URL")
  [ -n "$FORK_CHAIN_ID" ] || FORK_CHAIN_ID=$(cast chain-id --rpc-url "$FORK_URL")
  [ -n "$DEPLOYER" ] || DEPLOYER=$anvil_account_0

  if [ ${#DEPLOYER} = 42 ]; then
    impersonating=yes
  fi
}

ensure_not_running() {
  [ ! -f "$pidfile" ] || die "Already running."
}

ensure_running() {
  [ -f "$pidfile" ] || die "Not running."
}

start() {
  anvil=(
    anvil
      --fork-url "$FORK_URL"
      --fork-block-number "$FORK_BLOCK_NUMBER"
      --fork-chain-id "$FORK_CHAIN_ID"
      --chain-id "$FORK_CHAIN_ID"
  )

  if [ "$impersonating" = yes ]; then
    anvil+=( --auto-impersonate )
  fi

  nohup "${anvil[@]}" &> "$logfile" &
  echo $! > "$pidfile"
}

sourcify_start() {
  sourcify=(
    docker run
      -d
      -p "$sourcify_port:5555"
      -v "./$sourcify_chains:/home/app/services/server/dist/sourcify-chains.json"
      -v "./$sourcify_config:/home/app/services/server/dist/config/local.js"
      -e NODE_ENV=
      --rm
      ghcr.io/ethereum/sourcify/server:$sourcify_version
  )

  sourcify_container=$("${sourcify[@]}")
}

sourcify_stop() {
  docker kill "$sourcify_container"
}

# XXX the requests from sourcify are crashing anvil; don't verify for now
deploy() {
  deploy=(
    ./deploy
      --debug
      --rpc-url "$E2E_RPC_URL"
      --chain-id "$FORK_CHAIN_ID"
      --deployer "$DEPLOYER"
      --skip-confirmation
      # --verify
      # --verifier sourcify
      # --verifier-url "http://localhost:$sourcify_port"
  )

  if [ "$impersonating" = yes ]; then
    deploy+=( --unlocked )
  fi

  # sourcify_start
  "${deploy[@]}" "$@"
  # sourcify_stop
}

e2e() {
  forge test --match-path test/E2E.t.sol "$@"
}

stop() {
  kill "$(cat "$pidfile")" || echo "Deleting stale '$pidfile'."
  rm "$pidfile"
}

############
### Main ###
############

if [ $# -eq 0 ]; then
  usage
  exit
fi

cmd=$1
shift

case $cmd in
  start)
    ensure_not_running
    init_env
    start
    if [ "$1" = "--deploy" ]; then sleep 2; deploy; fi
    ;;
  deploy)
    ensure_running
    init_env
    deploy "$@"
    ;;
  e2e)
    ensure_running
    e2e "$@"
    ;;
  stop)
    ensure_running
    stop
    ;;
  *)
    echo "Bad command '$cmd'."
    echo
    usage
    exit 1
    ;;
esac
