import z from "zod";
import { zAddress } from "./zod-utils";

export const EnvSchema = z.object({
  APP_VERSION: z.string(),
  CHAIN_ID: z.string(),
  COMMIT_HASH: z.string(),
  CONTRACT_ACTIVE_POOL: zAddress(),
  CONTRACT_BOLD_TOKEN: zAddress(),
  CONTRACT_BORROWER_OPERATIONS: zAddress(),
  CONTRACT_COLL_SURPLUS_POOL: zAddress(),
  CONTRACT_DEFAULT_POOL: zAddress(),
  CONTRACT_FUNCTION_CALLER: zAddress(),
  CONTRACT_GAS_POOL: zAddress(),
  CONTRACT_HINT_HELPERS: zAddress(),
  CONTRACT_PRICE_FEED_TESTNET: zAddress(),
  CONTRACT_SORTED_TROVES: zAddress(),
  CONTRACT_STABILITY_POOL: zAddress(),
  CONTRACT_TROVE_MANAGER: zAddress(),
  WALLET_CONNECT_PROJECT_ID: z.string(),
}).transform((val) => ({
  ...val,
  CHAIN_ID: parseInt(val.CHAIN_ID, 10),
}));

export type Env = z.infer<typeof EnvSchema>;

export const {
  APP_VERSION,
  CHAIN_ID,
  COMMIT_HASH,
  CONTRACT_ACTIVE_POOL,
  CONTRACT_BOLD_TOKEN,
  CONTRACT_BORROWER_OPERATIONS,
  CONTRACT_COLL_SURPLUS_POOL,
  CONTRACT_DEFAULT_POOL,
  CONTRACT_FUNCTION_CALLER,
  CONTRACT_GAS_POOL,
  CONTRACT_HINT_HELPERS,
  CONTRACT_PRICE_FEED_TESTNET,
  CONTRACT_SORTED_TROVES,
  CONTRACT_STABILITY_POOL,
  CONTRACT_TROVE_MANAGER,
  WALLET_CONNECT_PROJECT_ID,
} = EnvSchema.parse({
  APP_VERSION: process.env.APP_VERSION,
  CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
  COMMIT_HASH: process.env.COMMIT_HASH,
  CONTRACT_ACTIVE_POOL: process.env.NEXT_PUBLIC_CONTRACT_ACTIVE_POOL,
  CONTRACT_BOLD_TOKEN: process.env.NEXT_PUBLIC_CONTRACT_BOLD_TOKEN,
  CONTRACT_BORROWER_OPERATIONS: process.env.NEXT_PUBLIC_CONTRACT_BORROWER_OPERATIONS,
  CONTRACT_COLL_SURPLUS_POOL: process.env.NEXT_PUBLIC_CONTRACT_COLL_SURPLUS_POOL,
  CONTRACT_DEFAULT_POOL: process.env.NEXT_PUBLIC_CONTRACT_DEFAULT_POOL,
  CONTRACT_FUNCTION_CALLER: process.env.NEXT_PUBLIC_CONTRACT_FUNCTION_CALLER,
  CONTRACT_GAS_POOL: process.env.NEXT_PUBLIC_CONTRACT_GAS_POOL,
  CONTRACT_HINT_HELPERS: process.env.NEXT_PUBLIC_CONTRACT_HINT_HELPERS,
  CONTRACT_PRICE_FEED_TESTNET: process.env.NEXT_PUBLIC_CONTRACT_PRICE_FEED_TESTNET,
  CONTRACT_SORTED_TROVES: process.env.NEXT_PUBLIC_CONTRACT_SORTED_TROVES,
  CONTRACT_STABILITY_POOL: process.env.NEXT_PUBLIC_CONTRACT_STABILITY_POOL,
  CONTRACT_TROVE_MANAGER: process.env.NEXT_PUBLIC_CONTRACT_TROVE_MANAGER,
  WALLET_CONNECT_PROJECT_ID: process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
});
