// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const ActivePool = [{ "type": "receive", "stateMutability": "payable" }, {
  "type": "function",
  "name": "NAME",
  "inputs": [],
  "outputs": [{ "name": "", "type": "string", "internalType": "string" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "borrowerOperationsAddress",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "decreaseBoldDebt",
  "inputs": [{ "name": "_amount", "type": "uint256", "internalType": "uint256" }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "defaultPoolAddress",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "getBoldDebt",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "getETH",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "increaseBoldDebt",
  "inputs": [{ "name": "_amount", "type": "uint256", "internalType": "uint256" }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "isOwner",
  "inputs": [],
  "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "owner",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "sendETH",
  "inputs": [{ "name": "_account", "type": "address", "internalType": "address" }, {
    "name": "_amount",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "setAddresses",
  "inputs": [
    { "name": "_borrowerOperationsAddress", "type": "address", "internalType": "address" },
    { "name": "_troveManagerAddress", "type": "address", "internalType": "address" },
    { "name": "_stabilityPoolAddress", "type": "address", "internalType": "address" },
    { "name": "_defaultPoolAddress", "type": "address", "internalType": "address" },
  ],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "stabilityPoolAddress",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "troveManagerAddress",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
  "stateMutability": "view",
}, {
  "type": "event",
  "name": "ActivePoolBoldDebtUpdated",
  "inputs": [{ "name": "_boldDebt", "type": "uint256", "indexed": false, "internalType": "uint256" }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "ActivePoolETHBalanceUpdated",
  "inputs": [{ "name": "_ETH", "type": "uint256", "indexed": false, "internalType": "uint256" }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "BorrowerOperationsAddressChanged",
  "inputs": [{
    "name": "_newBorrowerOperationsAddress",
    "type": "address",
    "indexed": false,
    "internalType": "address",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "DefaultPoolAddressChanged",
  "inputs": [{ "name": "_newDefaultPoolAddress", "type": "address", "indexed": false, "internalType": "address" }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "EtherSent",
  "inputs": [{ "name": "_to", "type": "address", "indexed": false, "internalType": "address" }, {
    "name": "_amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "OwnershipTransferred",
  "inputs": [{ "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" }, {
    "name": "newOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "StabilityPoolAddressChanged",
  "inputs": [{ "name": "_newStabilityPoolAddress", "type": "address", "indexed": false, "internalType": "address" }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "TroveManagerAddressChanged",
  "inputs": [{ "name": "_newTroveManagerAddress", "type": "address", "indexed": false, "internalType": "address" }],
  "anonymous": false,
}] as const;
