// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const DebtInFrontHelper = [{
  "type": "constructor",
  "inputs": [{ "name": "_collateralRegistry", "type": "address", "internalType": "contract ICollateralRegistry" }, {
    "name": "_hintHelpers",
    "type": "address",
    "internalType": "contract IHintHelpers",
  }],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "collateralRegistry",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "contract ICollateralRegistry" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "getDebtBetweenInterestRateAndTrove",
  "inputs": [
    { "name": "_collIndex", "type": "uint256", "internalType": "uint256" },
    { "name": "_interestRateLo", "type": "uint256", "internalType": "uint256" },
    { "name": "_interestRateHi", "type": "uint256", "internalType": "uint256" },
    { "name": "_troveIdToStopAt", "type": "uint256", "internalType": "uint256" },
    { "name": "_hintId", "type": "uint256", "internalType": "uint256" },
    { "name": "_numTrials", "type": "uint256", "internalType": "uint256" },
  ],
  "outputs": [{ "name": "debt", "type": "uint256", "internalType": "uint256" }, {
    "name": "blockTimestamp",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "getDebtBetweenInterestRates",
  "inputs": [
    { "name": "_collIndex", "type": "uint256", "internalType": "uint256" },
    { "name": "_interestRateLo", "type": "uint256", "internalType": "uint256" },
    { "name": "_interestRateHi", "type": "uint256", "internalType": "uint256" },
    { "name": "_excludedTroveId", "type": "uint256", "internalType": "uint256" },
    { "name": "_hintId", "type": "uint256", "internalType": "uint256" },
    { "name": "_numTrials", "type": "uint256", "internalType": "uint256" },
  ],
  "outputs": [{ "name": "debt", "type": "uint256", "internalType": "uint256" }, {
    "name": "blockTimestamp",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "hintHelpers",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "contract IHintHelpers" }],
  "stateMutability": "view",
}] as const;
