// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const GasPool = [{
  "type": "constructor",
  "inputs": [{ "name": "_weth", "type": "address", "internalType": "contract IWETH" }, {
    "name": "_borrowerOperations",
    "type": "address",
    "internalType": "contract IBorrowerOperations",
  }, { "name": "_troveManager", "type": "address", "internalType": "contract ITroveManager" }],
  "stateMutability": "nonpayable",
}] as const;
