// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const GasPool = [{
  "type": "constructor",
  "inputs": [{ "name": "_addressesRegistry", "type": "address", "internalType": "contract IAddressesRegistry" }],
  "stateMutability": "nonpayable",
}] as const;
