export const Governance = [
  {
    "type": "constructor",
    "inputs": [
      { "name": "_lqty", "type": "address", "internalType": "address" },
      { "name": "_lusd", "type": "address", "internalType": "address" },
      { "name": "_stakingV1", "type": "address", "internalType": "address" },
      { "name": "_bold", "type": "address", "internalType": "address" },
      {
        "name": "_config",
        "type": "tuple",
        "internalType": "struct IGovernance.Configuration",
        "components": [
          { "name": "registrationFee", "type": "uint128", "internalType": "uint128" },
          { "name": "registrationThresholdFactor", "type": "uint128", "internalType": "uint128" },
          { "name": "unregistrationThresholdFactor", "type": "uint128", "internalType": "uint128" },
          { "name": "registrationWarmUpPeriod", "type": "uint16", "internalType": "uint16" },
          { "name": "unregistrationAfterEpochs", "type": "uint16", "internalType": "uint16" },
          { "name": "votingThresholdFactor", "type": "uint128", "internalType": "uint128" },
          { "name": "minClaim", "type": "uint88", "internalType": "uint88" },
          { "name": "minAccrual", "type": "uint88", "internalType": "uint88" },
          { "name": "epochStart", "type": "uint32", "internalType": "uint32" },
          { "name": "epochDuration", "type": "uint32", "internalType": "uint32" },
          { "name": "epochVotingCutoff", "type": "uint32", "internalType": "uint32" },
        ],
      },
      { "name": "_initiatives", "type": "address[]", "internalType": "address[]" },
    ],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "EPOCH_DURATION",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "EPOCH_START",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "EPOCH_VOTING_CUTOFF",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "MIN_ACCRUAL",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "MIN_CLAIM",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "REGISTRATION_FEE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "REGISTRATION_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "REGISTRATION_WARM_UP_PERIOD",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "UNREGISTRATION_AFTER_EPOCHS",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "UNREGISTRATION_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "VOTING_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "allocateLQTY",
    "inputs": [{ "name": "_initiatives", "type": "address[]", "internalType": "address[]" }, {
      "name": "_deltaLQTYVotes",
      "type": "int176[]",
      "internalType": "int176[]",
    }, { "name": "_deltaLQTYVetos", "type": "int176[]", "internalType": "int176[]" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "bold",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IERC20" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "boldAccrued",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "calculateVotingThreshold",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "claimForInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "claimFromStakingV1",
    "inputs": [{ "name": "_rewardRecipient", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "accruedLUSD", "type": "uint256", "internalType": "uint256" }, {
      "name": "accruedETH",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "deployUserProxy",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositLQTY",
    "inputs": [{ "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositLQTYViaPermit",
    "inputs": [{ "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" }, {
      "name": "_permitParams",
      "type": "tuple",
      "internalType": "struct PermitParams",
      "components": [
        { "name": "owner", "type": "address", "internalType": "address" },
        { "name": "spender", "type": "address", "internalType": "address" },
        { "name": "value", "type": "uint256", "internalType": "uint256" },
        { "name": "deadline", "type": "uint256", "internalType": "uint256" },
        { "name": "v", "type": "uint8", "internalType": "uint8" },
        { "name": "r", "type": "bytes32", "internalType": "bytes32" },
        { "name": "s", "type": "bytes32", "internalType": "bytes32" },
      ],
    }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "deriveUserProxyAddress",
    "inputs": [{ "name": "_user", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "epoch",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint16", "internalType": "uint16" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "epochStart",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint32", "internalType": "uint32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "globalState",
    "inputs": [],
    "outputs": [{ "name": "countedVoteLQTY", "type": "uint88", "internalType": "uint88" }, {
      "name": "countedVoteLQTYAverageTimestamp",
      "type": "uint32",
      "internalType": "uint32",
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "initiativeStates",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "voteLQTY", "type": "uint88", "internalType": "uint88" },
      { "name": "vetoLQTY", "type": "uint88", "internalType": "uint88" },
      { "name": "averageStakingTimestampVoteLQTY", "type": "uint32", "internalType": "uint32" },
      { "name": "averageStakingTimestampVetoLQTY", "type": "uint32", "internalType": "uint32" },
      { "name": "counted", "type": "uint16", "internalType": "uint16" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "lqty",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IERC20" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "lqtyAllocatedByUserToInitiative",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }, {
      "name": "",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [{ "name": "voteLQTY", "type": "uint88", "internalType": "uint88" }, {
      "name": "vetoLQTY",
      "type": "uint88",
      "internalType": "uint88",
    }, { "name": "atEpoch", "type": "uint16", "internalType": "uint16" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "lqtyToVotes",
    "inputs": [{ "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" }, {
      "name": "_currentTimestamp",
      "type": "uint256",
      "internalType": "uint256",
    }, { "name": "_averageTimestamp", "type": "uint32", "internalType": "uint32" }],
    "outputs": [{ "name": "", "type": "uint240", "internalType": "uint240" }],
    "stateMutability": "pure",
  },
  {
    "type": "function",
    "name": "multicall",
    "inputs": [{ "name": "data", "type": "bytes[]", "internalType": "bytes[]" }],
    "outputs": [{ "name": "results", "type": "bytes[]", "internalType": "bytes[]" }],
    "stateMutability": "payable",
  },
  {
    "type": "function",
    "name": "registerInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "registeredInitiatives",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint16", "internalType": "uint16" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "secondsWithinEpoch",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint32", "internalType": "uint32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "snapshotVotesForInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [{
      "name": "voteSnapshot",
      "type": "tuple",
      "internalType": "struct IGovernance.VoteSnapshot",
      "components": [{ "name": "votes", "type": "uint240", "internalType": "uint240" }, {
        "name": "forEpoch",
        "type": "uint16",
        "internalType": "uint16",
      }],
    }, {
      "name": "initiativeVoteSnapshot",
      "type": "tuple",
      "internalType": "struct IGovernance.InitiativeVoteSnapshot",
      "components": [{ "name": "votes", "type": "uint224", "internalType": "uint224" }, {
        "name": "forEpoch",
        "type": "uint16",
        "internalType": "uint16",
      }, { "name": "lastCountedEpoch", "type": "uint16", "internalType": "uint16" }],
    }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "stakingV1",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract ILQTYStaking" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "unregisterInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "userProxyImplementation",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "userStates",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "allocatedLQTY", "type": "uint88", "internalType": "uint88" }, {
      "name": "averageStakingTimestamp",
      "type": "uint32",
      "internalType": "uint32",
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "votesForInitiativeSnapshot",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "votes", "type": "uint224", "internalType": "uint224" }, {
      "name": "forEpoch",
      "type": "uint16",
      "internalType": "uint16",
    }, { "name": "lastCountedEpoch", "type": "uint16", "internalType": "uint16" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "votesSnapshot",
    "inputs": [],
    "outputs": [{ "name": "votes", "type": "uint240", "internalType": "uint240" }, {
      "name": "forEpoch",
      "type": "uint16",
      "internalType": "uint16",
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "withdrawLQTY",
    "inputs": [{ "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "event",
    "name": "AllocateLQTY",
    "inputs": [
      { "name": "user", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "initiative", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "deltaVoteLQTY", "type": "int256", "indexed": false, "internalType": "int256" },
      { "name": "deltaVetoLQTY", "type": "int256", "indexed": false, "internalType": "int256" },
      { "name": "atEpoch", "type": "uint16", "indexed": false, "internalType": "uint16" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "ClaimForInitiative",
    "inputs": [{ "name": "initiative", "type": "address", "indexed": false, "internalType": "address" }, {
      "name": "bold",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }, { "name": "forEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "DeployUserProxy",
    "inputs": [{ "name": "user", "type": "address", "indexed": true, "internalType": "address" }, {
      "name": "userProxy",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "DepositLQTY",
    "inputs": [{ "name": "user", "type": "address", "indexed": false, "internalType": "address" }, {
      "name": "depositedLQTY",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "RegisterInitiative",
    "inputs": [{ "name": "initiative", "type": "address", "indexed": false, "internalType": "address" }, {
      "name": "registrant",
      "type": "address",
      "indexed": false,
      "internalType": "address",
    }, { "name": "atEpoch", "type": "uint16", "indexed": false, "internalType": "uint16" }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "SnapshotVotes",
    "inputs": [{ "name": "votes", "type": "uint240", "indexed": false, "internalType": "uint240" }, {
      "name": "forEpoch",
      "type": "uint16",
      "indexed": false,
      "internalType": "uint16",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "SnapshotVotesForInitiative",
    "inputs": [{ "name": "initiative", "type": "address", "indexed": false, "internalType": "address" }, {
      "name": "votes",
      "type": "uint240",
      "indexed": false,
      "internalType": "uint240",
    }, { "name": "forEpoch", "type": "uint16", "indexed": false, "internalType": "uint16" }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "UnregisterInitiative",
    "inputs": [{ "name": "initiative", "type": "address", "indexed": false, "internalType": "address" }, {
      "name": "atEpoch",
      "type": "uint16",
      "indexed": false,
      "internalType": "uint16",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "WithdrawLQTY",
    "inputs": [
      { "name": "user", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "withdrawnLQTY", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "accruedLUSD", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "accruedETH", "type": "uint256", "indexed": false, "internalType": "uint256" },
    ],
    "anonymous": false,
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [{ "name": "target", "type": "address", "internalType": "address" }],
  },
  {
    "type": "error",
    "name": "AddressInsufficientBalance",
    "inputs": [{ "name": "account", "type": "address", "internalType": "address" }],
  },
  { "type": "error", "name": "ERC1167FailedCreateClone", "inputs": [] },
  { "type": "error", "name": "FailedInnerCall", "inputs": [] },
  { "type": "error", "name": "ReentrancyGuardReentrantCall", "inputs": [] },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [{ "name": "token", "type": "address", "internalType": "address" }],
  },
] as const;

