export const Governance = [
  {
    "type": "constructor",
    "inputs": [
      { "name": "_lqty", "type": "address", "internalType": "address" },
      { "name": "_lusd", "type": "address", "internalType": "address" },
      { "name": "_stakingV1", "type": "address", "internalType": "address" },
      { "name": "_bold", "type": "address", "internalType": "address" },
      {
        "name": "_config",
        "type": "tuple",
        "internalType": "struct IGovernance.Configuration",
        "components": [
          { "name": "registrationFee", "type": "uint128", "internalType": "uint128" },
          { "name": "registrationThresholdFactor", "type": "uint128", "internalType": "uint128" },
          { "name": "unregistrationThresholdFactor", "type": "uint128", "internalType": "uint128" },
          { "name": "unregistrationAfterEpochs", "type": "uint16", "internalType": "uint16" },
          { "name": "votingThresholdFactor", "type": "uint128", "internalType": "uint128" },
          { "name": "minClaim", "type": "uint88", "internalType": "uint88" },
          { "name": "minAccrual", "type": "uint88", "internalType": "uint88" },
          { "name": "epochStart", "type": "uint32", "internalType": "uint32" },
          { "name": "epochDuration", "type": "uint32", "internalType": "uint32" },
          { "name": "epochVotingCutoff", "type": "uint32", "internalType": "uint32" },
        ],
      },
      { "name": "_owner", "type": "address", "internalType": "address" },
      { "name": "_initiatives", "type": "address[]", "internalType": "address[]" },
    ],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "EPOCH_DURATION",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "EPOCH_START",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "EPOCH_VOTING_CUTOFF",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "MIN_ACCRUAL",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "MIN_CLAIM",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "REGISTRATION_FEE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "REGISTRATION_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "TIMESTAMP_PRECISION",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint120", "internalType": "uint120" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "UNREGISTRATION_AFTER_EPOCHS",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "UNREGISTRATION_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "VOTING_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "allocateLQTY",
    "inputs": [
      { "name": "_initiativesToReset", "type": "address[]", "internalType": "address[]" },
      { "name": "_initiatives", "type": "address[]", "internalType": "address[]" },
      { "name": "_absoluteLQTYVotes", "type": "int88[]", "internalType": "int88[]" },
      { "name": "_absoluteLQTYVetos", "type": "int88[]", "internalType": "int88[]" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "bold",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IERC20" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "boldAccrued",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "calculateVotingThreshold",
    "inputs": [{ "name": "_votes", "type": "uint256", "internalType": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "calculateVotingThreshold",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "claimForInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "claimFromStakingV1",
    "inputs": [{ "name": "_rewardRecipient", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "lusdSent", "type": "uint256", "internalType": "uint256" },
      { "name": "ethSent", "type": "uint256", "internalType": "uint256" },
    ],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "deployUserProxy",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositLQTY",
    "inputs": [{ "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositLQTY",
    "inputs": [
      { "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" },
      { "name": "_doSendRewards", "type": "bool", "internalType": "bool" },
      { "name": "_recipient", "type": "address", "internalType": "address" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositLQTYViaPermit",
    "inputs": [
      { "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" },
      {
        "name": "_permitParams",
        "type": "tuple",
        "internalType": "struct PermitParams",
        "components": [
          { "name": "owner", "type": "address", "internalType": "address" },
          { "name": "spender", "type": "address", "internalType": "address" },
          { "name": "value", "type": "uint256", "internalType": "uint256" },
          { "name": "deadline", "type": "uint256", "internalType": "uint256" },
          { "name": "v", "type": "uint8", "internalType": "uint8" },
          { "name": "r", "type": "bytes32", "internalType": "bytes32" },
          { "name": "s", "type": "bytes32", "internalType": "bytes32" },
        ],
      },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositLQTYViaPermit",
    "inputs": [
      { "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" },
      {
        "name": "_permitParams",
        "type": "tuple",
        "internalType": "struct PermitParams",
        "components": [
          { "name": "owner", "type": "address", "internalType": "address" },
          { "name": "spender", "type": "address", "internalType": "address" },
          { "name": "value", "type": "uint256", "internalType": "uint256" },
          { "name": "deadline", "type": "uint256", "internalType": "uint256" },
          { "name": "v", "type": "uint8", "internalType": "uint8" },
          { "name": "r", "type": "bytes32", "internalType": "bytes32" },
          { "name": "s", "type": "bytes32", "internalType": "bytes32" },
        ],
      },
      { "name": "_doSendRewards", "type": "bool", "internalType": "bool" },
      { "name": "_recipient", "type": "address", "internalType": "address" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "deriveUserProxyAddress",
    "inputs": [{ "name": "_user", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "epoch",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint16", "internalType": "uint16" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "epochStart",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint32", "internalType": "uint32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getInitiativeSnapshotAndState",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [
      {
        "name": "initiativeSnapshot",
        "type": "tuple",
        "internalType": "struct IGovernance.InitiativeVoteSnapshot",
        "components": [
          { "name": "votes", "type": "uint224", "internalType": "uint224" },
          { "name": "forEpoch", "type": "uint16", "internalType": "uint16" },
          { "name": "lastCountedEpoch", "type": "uint16", "internalType": "uint16" },
          { "name": "vetos", "type": "uint224", "internalType": "uint224" },
        ],
      },
      {
        "name": "initiativeState",
        "type": "tuple",
        "internalType": "struct IGovernance.InitiativeState",
        "components": [
          { "name": "voteLQTY", "type": "uint88", "internalType": "uint88" },
          { "name": "vetoLQTY", "type": "uint88", "internalType": "uint88" },
          { "name": "averageStakingTimestampVoteLQTY", "type": "uint120", "internalType": "uint120" },
          { "name": "averageStakingTimestampVetoLQTY", "type": "uint120", "internalType": "uint120" },
          { "name": "lastEpochClaim", "type": "uint16", "internalType": "uint16" },
        ],
      },
      { "name": "shouldUpdate", "type": "bool", "internalType": "bool" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getInitiativeState",
    "inputs": [
      { "name": "_initiative", "type": "address", "internalType": "address" },
      {
        "name": "_votesSnapshot",
        "type": "tuple",
        "internalType": "struct IGovernance.VoteSnapshot",
        "components": [
          { "name": "votes", "type": "uint240", "internalType": "uint240" },
          { "name": "forEpoch", "type": "uint16", "internalType": "uint16" },
        ],
      },
      {
        "name": "_votesForInitiativeSnapshot",
        "type": "tuple",
        "internalType": "struct IGovernance.InitiativeVoteSnapshot",
        "components": [
          { "name": "votes", "type": "uint224", "internalType": "uint224" },
          { "name": "forEpoch", "type": "uint16", "internalType": "uint16" },
          { "name": "lastCountedEpoch", "type": "uint16", "internalType": "uint16" },
          { "name": "vetos", "type": "uint224", "internalType": "uint224" },
        ],
      },
      {
        "name": "_initiativeState",
        "type": "tuple",
        "internalType": "struct IGovernance.InitiativeState",
        "components": [
          { "name": "voteLQTY", "type": "uint88", "internalType": "uint88" },
          { "name": "vetoLQTY", "type": "uint88", "internalType": "uint88" },
          { "name": "averageStakingTimestampVoteLQTY", "type": "uint120", "internalType": "uint120" },
          { "name": "averageStakingTimestampVetoLQTY", "type": "uint120", "internalType": "uint120" },
          { "name": "lastEpochClaim", "type": "uint16", "internalType": "uint16" },
        ],
      },
    ],
    "outputs": [
      { "name": "status", "type": "uint8", "internalType": "enum IGovernance.InitiativeStatus" },
      { "name": "lastEpochClaim", "type": "uint16", "internalType": "uint16" },
      { "name": "claimableAmount", "type": "uint256", "internalType": "uint256" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getInitiativeState",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "status", "type": "uint8", "internalType": "enum IGovernance.InitiativeStatus" },
      { "name": "lastEpochClaim", "type": "uint16", "internalType": "uint16" },
      { "name": "claimableAmount", "type": "uint256", "internalType": "uint256" },
    ],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "getLatestVotingThreshold",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getTotalVotesAndState",
    "inputs": [],
    "outputs": [
      {
        "name": "snapshot",
        "type": "tuple",
        "internalType": "struct IGovernance.VoteSnapshot",
        "components": [
          { "name": "votes", "type": "uint240", "internalType": "uint240" },
          { "name": "forEpoch", "type": "uint16", "internalType": "uint16" },
        ],
      },
      {
        "name": "state",
        "type": "tuple",
        "internalType": "struct IGovernance.GlobalState",
        "components": [
          { "name": "countedVoteLQTY", "type": "uint88", "internalType": "uint88" },
          { "name": "countedVoteLQTYAverageTimestamp", "type": "uint120", "internalType": "uint120" },
        ],
      },
      { "name": "shouldUpdate", "type": "bool", "internalType": "bool" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "globalState",
    "inputs": [],
    "outputs": [
      { "name": "countedVoteLQTY", "type": "uint88", "internalType": "uint88" },
      { "name": "countedVoteLQTYAverageTimestamp", "type": "uint120", "internalType": "uint120" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "initiativeStates",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "voteLQTY", "type": "uint88", "internalType": "uint88" },
      { "name": "vetoLQTY", "type": "uint88", "internalType": "uint88" },
      { "name": "averageStakingTimestampVoteLQTY", "type": "uint120", "internalType": "uint120" },
      { "name": "averageStakingTimestampVetoLQTY", "type": "uint120", "internalType": "uint120" },
      { "name": "lastEpochClaim", "type": "uint16", "internalType": "uint16" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "isOwner",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "lqty",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IERC20" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "lqtyAllocatedByUserToInitiative",
    "inputs": [
      { "name": "", "type": "address", "internalType": "address" },
      { "name": "", "type": "address", "internalType": "address" },
    ],
    "outputs": [
      { "name": "voteLQTY", "type": "uint88", "internalType": "uint88" },
      { "name": "vetoLQTY", "type": "uint88", "internalType": "uint88" },
      { "name": "atEpoch", "type": "uint16", "internalType": "uint16" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "lqtyToVotes",
    "inputs": [
      { "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" },
      { "name": "_currentTimestamp", "type": "uint120", "internalType": "uint120" },
      { "name": "_averageTimestamp", "type": "uint120", "internalType": "uint120" },
    ],
    "outputs": [{ "name": "", "type": "uint208", "internalType": "uint208" }],
    "stateMutability": "pure",
  },
  {
    "type": "function",
    "name": "multiDelegateCall",
    "inputs": [{ "name": "inputs", "type": "bytes[]", "internalType": "bytes[]" }],
    "outputs": [{ "name": "returnValues", "type": "bytes[]", "internalType": "bytes[]" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "registerInitialInitiatives",
    "inputs": [{ "name": "_initiatives", "type": "address[]", "internalType": "address[]" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "registerInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "registeredInitiatives",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint16", "internalType": "uint16" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "resetAllocations",
    "inputs": [
      { "name": "_initiativesToReset", "type": "address[]", "internalType": "address[]" },
      { "name": "checkAll", "type": "bool", "internalType": "bool" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "secondsWithinEpoch",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint32", "internalType": "uint32" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "snapshotVotesForInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [
      {
        "name": "voteSnapshot",
        "type": "tuple",
        "internalType": "struct IGovernance.VoteSnapshot",
        "components": [
          { "name": "votes", "type": "uint240", "internalType": "uint240" },
          { "name": "forEpoch", "type": "uint16", "internalType": "uint16" },
        ],
      },
      {
        "name": "initiativeVoteSnapshot",
        "type": "tuple",
        "internalType": "struct IGovernance.InitiativeVoteSnapshot",
        "components": [
          { "name": "votes", "type": "uint224", "internalType": "uint224" },
          { "name": "forEpoch", "type": "uint16", "internalType": "uint16" },
          { "name": "lastCountedEpoch", "type": "uint16", "internalType": "uint16" },
          { "name": "vetos", "type": "uint224", "internalType": "uint224" },
        ],
      },
    ],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "stakingV1",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract ILQTYStaking" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "unregisterInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "userProxyImplementation",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "userStates",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "allocatedLQTY", "type": "uint88", "internalType": "uint88" },
      { "name": "averageStakingTimestamp", "type": "uint120", "internalType": "uint120" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "votesForInitiativeSnapshot",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "votes", "type": "uint224", "internalType": "uint224" },
      { "name": "forEpoch", "type": "uint16", "internalType": "uint16" },
      { "name": "lastCountedEpoch", "type": "uint16", "internalType": "uint16" },
      { "name": "vetos", "type": "uint224", "internalType": "uint224" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "votesSnapshot",
    "inputs": [],
    "outputs": [
      { "name": "votes", "type": "uint240", "internalType": "uint240" },
      { "name": "forEpoch", "type": "uint16", "internalType": "uint16" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "withdrawLQTY",
    "inputs": [{ "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "withdrawLQTY",
    "inputs": [
      { "name": "_lqtyAmount", "type": "uint88", "internalType": "uint88" },
      { "name": "_doSendRewards", "type": "bool", "internalType": "bool" },
      { "name": "_recipient", "type": "address", "internalType": "address" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "event",
    "name": "AllocateLQTY",
    "inputs": [
      { "name": "user", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "initiative", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "deltaVoteLQTY", "type": "int256", "indexed": false, "internalType": "int256" },
      { "name": "deltaVetoLQTY", "type": "int256", "indexed": false, "internalType": "int256" },
      { "name": "atEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "hookSuccess", "type": "bool", "indexed": false, "internalType": "bool" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "ClaimForInitiative",
    "inputs": [
      { "name": "initiative", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "bold", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "forEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "hookSuccess", "type": "bool", "indexed": false, "internalType": "bool" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "DeployUserProxy",
    "inputs": [
      { "name": "user", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "userProxy", "type": "address", "indexed": true, "internalType": "address" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "DepositLQTY",
    "inputs": [
      { "name": "user", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "rewardRecipient", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "lqtyAmount", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lusdReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lusdSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "ethReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "ethSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      { "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "newOwner", "type": "address", "indexed": true, "internalType": "address" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "RegisterInitiative",
    "inputs": [
      { "name": "initiative", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "registrant", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "atEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "hookSuccess", "type": "bool", "indexed": false, "internalType": "bool" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "SnapshotVotes",
    "inputs": [
      { "name": "votes", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "forEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "boldAccrued", "type": "uint256", "indexed": false, "internalType": "uint256" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "SnapshotVotesForInitiative",
    "inputs": [
      { "name": "initiative", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "votes", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "vetos", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "forEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "UnregisterInitiative",
    "inputs": [
      { "name": "initiative", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "atEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "hookSuccess", "type": "bool", "indexed": false, "internalType": "bool" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "WithdrawLQTY",
    "inputs": [
      { "name": "user", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "recipient", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "lqtyReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lqtySent", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lusdReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lusdSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "ethReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "ethSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
    ],
    "anonymous": false,
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [{ "name": "target", "type": "address", "internalType": "address" }],
  },
  {
    "type": "error",
    "name": "AddressInsufficientBalance",
    "inputs": [{ "name": "account", "type": "address", "internalType": "address" }],
  },
  { "type": "error", "name": "ERC1167FailedCreateClone", "inputs": [] },
  { "type": "error", "name": "FailedInnerCall", "inputs": [] },
  { "type": "error", "name": "ReentrancyGuardReentrantCall", "inputs": [] },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [{ "name": "token", "type": "address", "internalType": "address" }],
  },
] as const;
