// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const IExchangeHelpersV2 = [{
  "type": "function",
  "name": "quoteExactInput",
  "inputs": [{ "name": "_inputAmount", "type": "uint256", "internalType": "uint256" }, {
    "name": "_collToBold",
    "type": "bool",
    "internalType": "bool",
  }, { "name": "_collToken", "type": "address", "internalType": "address" }],
  "outputs": [{ "name": "outputAmount", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "quoteExactOutput",
  "inputs": [{ "name": "_outputAmount", "type": "uint256", "internalType": "uint256" }, {
    "name": "_collToBold",
    "type": "bool",
    "internalType": "bool",
  }, { "name": "_collToken", "type": "address", "internalType": "address" }],
  "outputs": [{ "name": "inputAmount", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "nonpayable",
}] as const;
