// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const PriceFeed = [{
  "type": "function",
  "name": "ETHUSD_TELLOR_REQ_ID",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "MAX_PRICE_DEVIATION_FROM_PREVIOUS_ROUND",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "MAX_PRICE_DIFFERENCE_BETWEEN_ORACLES",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "NAME",
  "inputs": [],
  "outputs": [{ "name": "", "type": "string", "internalType": "string" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "TARGET_DIGITS",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "TELLOR_DIGITS",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "TIMEOUT",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "fetchPrice",
  "inputs": [],
  "outputs": [{ "name": "_lastGoodPrice", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "isOwner",
  "inputs": [],
  "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "lastGoodPrice",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "owner",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "priceAggregator",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "contract AggregatorV3Interface" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "setAddresses",
  "inputs": [{ "name": "_priceAggregatorAddress", "type": "address", "internalType": "address" }, {
    "name": "_tellorCallerAddress",
    "type": "address",
    "internalType": "address",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "status",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint8", "internalType": "enum PriceFeed.Status" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "tellorCaller",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "contract ITellorCaller" }],
  "stateMutability": "view",
}, {
  "type": "event",
  "name": "LastGoodPriceUpdated",
  "inputs": [{ "name": "_lastGoodPrice", "type": "uint256", "indexed": false, "internalType": "uint256" }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "OwnershipTransferred",
  "inputs": [{ "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" }, {
    "name": "newOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "PriceFeedStatusChanged",
  "inputs": [{ "name": "newStatus", "type": "uint8", "indexed": false, "internalType": "enum PriceFeed.Status" }],
  "anonymous": false,
}] as const;
