// this file was generated by scripts/update-liquity-abis.ts
// please do not edit it manually
export const RedemptionHelper = [{
  "type": "constructor",
  "inputs": [{ "name": "_collateralRegistry", "type": "address", "internalType": "contract ICollateralRegistry" }, {
    "name": "_addresses",
    "type": "address[]",
    "internalType": "contract IAddressesRegistry[]",
  }],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "addresses",
  "inputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "outputs": [{ "name": "", "type": "address", "internalType": "contract IAddressesRegistry" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "boldToken",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "contract IBoldToken" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "collateralRegistry",
  "inputs": [],
  "outputs": [{ "name": "", "type": "address", "internalType": "contract ICollateralRegistry" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "numBranches",
  "inputs": [],
  "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "redeemCollateral",
  "inputs": [
    { "name": "_bold", "type": "uint256", "internalType": "uint256" },
    { "name": "_maxIterationsPerCollateral", "type": "uint256", "internalType": "uint256" },
    { "name": "_maxFeePct", "type": "uint256", "internalType": "uint256" },
    { "name": "_minCollRedeemed", "type": "uint256[]", "internalType": "uint256[]" },
  ],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "simulateRedemption",
  "inputs": [{ "name": "_bold", "type": "uint256", "internalType": "uint256" }, {
    "name": "_maxIterationsPerCollateral",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [{
    "name": "branch",
    "type": "tuple[]",
    "internalType": "struct IRedemptionHelper.SimulationContext[]",
    "components": [
      { "name": "troveManager", "type": "address", "internalType": "address" },
      { "name": "sortedTroves", "type": "address", "internalType": "address" },
      { "name": "redeemable", "type": "bool", "internalType": "bool" },
      { "name": "price", "type": "uint256", "internalType": "uint256" },
      { "name": "proportion", "type": "uint256", "internalType": "uint256" },
      { "name": "attemptedBold", "type": "uint256", "internalType": "uint256" },
      { "name": "redeemedBold", "type": "uint256", "internalType": "uint256" },
      { "name": "iterations", "type": "uint256", "internalType": "uint256" },
    ],
  }, { "name": "totalProportions", "type": "uint256", "internalType": "uint256" }],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "truncateRedemption",
  "inputs": [{ "name": "_bold", "type": "uint256", "internalType": "uint256" }, {
    "name": "_maxIterationsPerCollateral",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [{ "name": "truncatedBold", "type": "uint256", "internalType": "uint256" }, {
    "name": "feePct",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "redeemed",
    "type": "tuple[]",
    "internalType": "struct IRedemptionHelper.Redeemed[]",
    "components": [{ "name": "bold", "type": "uint256", "internalType": "uint256" }, {
      "name": "coll",
      "type": "uint256",
      "internalType": "uint256",
    }],
  }],
  "stateMutability": "nonpayable",
}] as const;
